### ISSUE TITLE
Feature Request : Enable the possibility to show the properties

### ISSUE THREAD

**Issue by MelodyDuplaix** [likemuuxi/obsidian-modal-opener#1]
This plugin is great. But, I use properties a lot, and I would like to view and edit also the properties in the note when I open a note in the modal. Is this possible to implement that ?

**Comment by likemuuxi** [comment]
I currently hide this section with CSS, but I'll either remove it or make it optional in the next version. If you want to implement the change now, you can delete it from the `style.css` file yourself.
```
.file-modal .metadata-container {
    display: none !important;
} 
```

**Comment by MelodyDuplaix** [comment]
Thanks for the answer.
To be honest, I didn't even think to look at the style of the plugin, but it was indeed so simple. I should have known it was just hidden. 
So, no problem for me. I still think that it could be an option in the settings, to make it simpler for less advanced users.

**Comment by likemuuxi** [comment]
Yes, I completely agree. I will gradually improve it.
