### ISSUE TITLE
[FR] Compability with the Note Toolbar Plugin

### ISSUE THREAD

**Issue by Moyf** [likemuuxi/obsidian-modal-opener#2]
Hi! [Note toolbar](https://github.com/chrisgurney/obsidian-note-toolbar) plugin will show double toolbars in modal window, is it possible to fix it?

![image](https://github.com/user-attachments/assets/d3f2c696-251b-4f83-a448-38d1cff997d7)

**Comment by likemuuxi** [comment]
已经解决，更新到最新版本即可

**Comment by Moyf** [comment]
> 已经解决，更新到最新版本即可

赞！👍🏻

**Comment by Moyf** [comment]
![image](https://github.com/user-attachments/assets/c2480b49-874b-497c-85ff-a2b9b99d586a)

噗……好像……更多了……

**Comment by likemuuxi** [comment]
奇怪欸  我这边测试没问题的

**Comment by Moyf** [comment]
原来是没更新成功……现在可以啦！
