### ISSUE TITLE
[Feature request] Mobile tapping to open

### ISSUE THREAD

**Issue by kulizivo** [likemuuxi/obsidian-modal-opener#3]
I was wondering if you could add a feature whereby instead of dragging the Link, you can instead double tap the link to produce the view.

**Comment by likemuuxi** [comment]
Double clicking may cause many conflicts, and I am not sure if this method is better. I need to decide after testing on the mobile device.

**Comment by likemuuxi** [comment]
最新版本支持了单击打开，移动端会更容易触发。
