### ISSUE TITLE
[提问] 想知道编辑模式下是怎么检测点击链接的？

### ISSUE THREAD

**Issue by Moyf** [likemuuxi/obsidian-modal-opener#5]
![image](https://github.com/user-attachments/assets/604c3351-b5b5-48a6-aade-731a57a0fc83)

我在点击 Rich Foot 插件生成的回链（上图的元素）的时候，提示没有链接。
这个元素的`href` 属性是存在的，所以想问问本插件是根据什么来判断链接的？

```html
<a class="cm-hmd-internal-link cm-underline" href="学习笔记/Obsidian/241126_RichFoot插件的自定义属性改进.md" data-href="学习笔记/Obsidian/241126_RichFoot插件的自定义属性改进.md" data-source-path="学习笔记/Obsidian/241130_RichFoot的二次改进：预览和过滤等.md">241126_RichFoot插件的自定义属性改进</a>
```

**Comment by likemuuxi** [comment]
在支持的Class中查找链接属性，这个应该是需要适配一下

**Comment by likemuuxi** [comment]
我尝试了下 是可以的
https://github.com/user-attachments/assets/0c5121a4-6695-4179-b74e-a1684ab7e3bc

**Comment by Moyf** [comment]
奇怪，我在阅读模式下可以，编辑模式下就点不开
https://github.com/user-attachments/assets/792f817a-f4a7-46af-99f3-1d9a8132c9bb

那我再试着排查一下原因，感谢！

**Comment by Moyf** [comment]
```js
  handleEditModeLink(editor) {
    const cursor = editor.getCursor();
    const line = editor.getLine(cursor.line);
    const linkMatch = this.findLinkAtPosition(line, cursor.ch);
    if (linkMatch) {
      this.openInFloatPreview(linkMatch);
    } else {
      new import_obsidian4.Notice(t("No link found at cursor position"));
    }
  }
```

想了一下是不是因为这样……
RichFoot 提供的附加链接并不是位于「页面内」，所以在这一步想要通过 Cursor 去获得 line 会失败，于是就报错。

但其实这一步已经获取到 `href` 了，这种情况下可以不用再通过 `handleEditModeLink` 来获取链接？ 🤔

**Comment by likemuuxi** [comment]
应该是光标位于文内的时候，优先检测光标当前行的链接导致的，我想想有没有办法适配一下

**Comment by likemuuxi** [comment]
已经适配了，更新到 [0.7.6](https://github.com/likemuuxi/obsidian-modal-opener/releases/tag/0.7.6) 即可
