### ISSUE TITLE
大佬，请问可以直接单击笔记内链接，打开笔记吗？

### ISSUE THREAD

**Issue by i-iooi-i** [likemuuxi/obsidian-modal-opener#7]
感谢大佬的插件，非常喜欢。

遇到一个问题，
现在好像只能按Alt触发，或者拖拽链接触发，
想问一下有没有办法可以通过单击笔记内的链接直接触发呢？

再次感谢大佬的插件哇。

**Comment by likemuuxi** [comment]
是可以的，但是单击需要精准控制点击的元素才可以避免非预期的行为，需要广泛的测试，如果可以的话，我这边给到你一个测试版，能帮我进行测试吗？
